name: Web Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC

jobs:
  test:
    runs-on: windows-latest  # Use Windows instead of Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci  # Faster than npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Tests
        run: npm test  # Adjust this based on your framework

      - name: Upload Test Results (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results/

      - name: Debug Info
        run: |
          google-chrome --version
          chromedriver --version
